version: 2
jobs:
  build:
    docker:
      # Bump cache key version below when changing elixir version
      - image: circleci/elixir:1.5.1
    # resource_class: medium+
    steps:
      - checkout
      - restore_cache:
          keys:
            - v2-dependency-cache-{{ checksum "mix.lock" }}
            - v2-dependency-cache
      - run: mix local.hex --force
      - run: mix local.rebar --force
      - run: mix deps.get
      - run: mix deps.compile
      - run: mix compile
      - run:
          command: mix compile
          environment:
            MIX_ENV: test
      - save_cache:
          key: v2-dependency-cache-{{ checksum "mix.lock" }}
          paths:
            - _build
            - deps
            - ~/.mix
      # - restore_cache:
      #     keys:
      #       - v1-plt-cache-{{ checksum "mix.lock" }}
      #       - v1-plt-cache
      # - run: mix dialyzer --plt
      # - save_cache:
      #     key: v1-plt-cache-{{ checksum "mix.lock" }}
      #     paths:
      #       - ~/.mix
      # - run: mix dialyzer --halt-exit-status
      - run: mix credo
      - run: mix test
