version: 2
jobs:
  build:
    docker:
      - image: circleci/elixir:1.4.5
    steps:
      - checkout
      - restore_cache:
          key: dependency-cache-{{ checksum "mix.lock" }}
      - run: mix local.hex --force
      - run: mix local.rebar --force
      - run: mix deps.get
      - run: mix deps.compile
      - run: mix compile
      # - run: mix dialyzer --plt
      - save_cache:
          key: dependency-cache={{ checksum "mix.lock" }}
          paths:
            - _build
            - deps
            - ~/.mix
      - run: mix credo
      # - run: mix dialyzer --halt-exit-status
      - run: mix test
